### ISSUE TITLE
Add a layer for the big icons in the middle of the card

### ISSUE THREAD

**Issue by Shaidar413** [Keldorb/MtgCardDeviders#1]
Love these things!
Would like a separate layer for the big icons in the middle of the card so those can be optional

I tinkered a bit with it and do not know how to actually message you so I'm writing it here :)

noticed that the grey (black) card was too high, pulled it down and did the same with the icons
added a outline layer for those that do not want the whole color or print on colored paper did not mess with the small icons though.
added a "flap" layer also for the small squares that stick up, so you can print the flaps in color and use outline for easy cutting.

Attached the updated .pdn file for the stuff i made if you want to implement them
[Basic Template with Edition layers_update.zip](https://github.com/Keldorb/MtgCardDeviders/files/2522015/Basic.Template.with.Edition.layers_update.zip)

**Comment by Keldorb** [comment]
hey @Shaidar413 ! 
Your improvments are highly welcome thanks for your work. 
I looked over it and edited some things that you maybe missed the white and gold Outline were a bit of. Big thanks to involve yourself! I will update the file any minute!
